name: chemprop

channels:
  - conda-forge
  - pytorch
  - rdkit

dependencies:
  - flask
  - GPy
  - hyperopt
  - numpy
  - pytorch
  - rdkit
  - scikit-learn
  - scipy
  - tensorboardX
  - tensorflow
  - torchvision
  - tqdm